-- Auto-derived canonical names for NULL rows (526 rows, with same-date merging)
-- Only updates rows where CanonicalRaceName IS NULL
-- Merges annotated with -- MERGED for review

USE [RaceResult]
GO

UPDATE dbo.Race SET CanonicalRaceName = '3 Points Challenge' WHERE raceid IN (25, 665) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = '5 Beaches Swim' WHERE raceid IN (22) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = '5 Beaches Swim - Coogee-Bondi' WHERE raceid IN (1477) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Across Lake Macquarie' WHERE raceid IN (966) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Across Newcastle Harbour' WHERE raceid IN (952) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Australia Day Aquathon - Wollongong' WHERE raceid IN (590) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Australia Day Aquathon -Swim' WHERE raceid IN (1116) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Australia Day Kids Aquathon -Swim' WHERE raceid IN (1118) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Australia Day Short Aquathon -Swim' WHERE raceid IN (1117) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Avalon' WHERE raceid IN (568, 588, 632, 673, 714, 752, 790, 823, 876, 946, 1027, 1101, 1102, 1217, 1218, 1294, 1295) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Avalon Around the Bend' WHERE raceid IN (1421, 1422, 1423) AND CanonicalRaceName IS NULL;  -- MERGED: 'Avalon Around the Bend', 'Avalon 1.5km', 'Avalon 1km'
UPDATE dbo.Race SET CanonicalRaceName = 'Avoca' WHERE raceid IN (584, 628, 668, 1133, 1134) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Avoca Beach Open' WHERE raceid IN (566) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Balina Lakeside Swim' WHERE raceid IN (1131, 1132) AND CanonicalRaceName IS NULL;  -- MERGED: 'Balina 850m', 'Balina Lakeside Swim'
UPDATE dbo.Race SET CanonicalRaceName = 'Balmoral' WHERE raceid IN (642, 688, 846, 899, 1055, 1094, 1095, 1209, 1210, 1407, 1408) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Balmoral Junior Swim' WHERE raceid IN (961, 1151) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Balmoral Swim for Cancer' WHERE raceid IN (410, 411, 412, 550, 551, 552, 615, 729, 771, 962, 1146, 1235) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Balmoral Vladswim' WHERE raceid IN (935, 936) AND CanonicalRaceName IS NULL;  -- MERGED: 'Balmoral 5km', 'Balmoral Vladswim 10km'
UPDATE dbo.Race SET CanonicalRaceName = 'Banana Boat Bondi To Bronte' WHERE raceid IN (564, 582) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Baths2Bar' WHERE raceid IN (741) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Bay to Boulders Swim' WHERE raceid IN (1148) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Bay to Breakers Hawks Nest' WHERE raceid IN (755) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Bilgola Ocean Swim' WHERE raceid IN (10, 11, 565, 583, 625, 664, 701, 749, 786, 819, 865, 931, 1045, 1127, 1128, 1204, 1205, 1284, 1285, 1377, 1378) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Black Head' WHERE raceid IN (1296, 1297) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Black Head - Head 2 Head' WHERE raceid IN (1219, 1220) AND CanonicalRaceName IS NULL;  -- MERGED: 'Black Head - Head 2 Head', 'Black Head 700m'
UPDATE dbo.Race SET CanonicalRaceName = 'Blackhead' WHERE raceid IN (870) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Blacksmiths' WHERE raceid IN (1255, 1256) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Bondi' WHERE raceid IN (972) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Bondi Bay Swim' WHERE raceid IN (1280) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Bondi Junior' WHERE raceid IN (1281, 1282) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Bondi Splash Series' WHERE raceid IN (1364) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Bondi To Bondi' WHERE raceid IN (1202) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Bondi to Bronte' WHERE raceid IN (748) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Bridge to Beach' WHERE raceid IN (804) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Brisbane Water' WHERE raceid IN (644, 645, 646) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Bronte Bay Swim' WHERE raceid IN (1091) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Bronte Junior' WHERE raceid IN (1092, 1093) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Broulee Bay to Breakers Ocean Swim' WHERE raceid IN (892, 960) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Byron Bay Mini' WHERE raceid IN (1258, 1259, 1342, 1343) AND CanonicalRaceName IS NULL;  -- MERGED: 'Byron Bay', 'Byron Bay Mini', 'Byron Bay Mini', 'Byron Bay'
UPDATE dbo.Race SET CanonicalRaceName = 'Byron Bay Winter Whales' WHERE raceid IN (607, 654, 696, 740, 777, 1066) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Captain Christie Classic' WHERE raceid IN (13, 672, 798) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Caves Beach Ocean Swim' WHERE raceid IN (597, 648, 680, 720, 767, 902, 959, 1142, 1337) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Chieftain Challenge' WHERE raceid IN (21) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Clarence River' WHERE raceid IN (702) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Clearwater Classic Jervis Bay' WHERE raceid IN (1143) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Coffs Coast' WHERE raceid IN (595) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Coffs Coast Swin' WHERE raceid IN (637) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Coffs Harbour' WHERE raceid IN (682, 723, 803, 1159, 1160, 1161, 1162) AND CanonicalRaceName IS NULL;  -- MERGED: 'Coffs Harbour', 'Coffs Harbour', 'Coffs Harbour', 'Coffs Harbour', 'Coffs 600m', 'Coffs 300m', 'Coffs 150m'
UPDATE dbo.Race SET CanonicalRaceName = 'Coogee to Bondi 5 Beaches' WHERE raceid IN (1283) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Cook Community Classic' WHERE raceid IN (39, 40, 811, 812, 919, 920, 1001, 1002, 1191, 1192, 1267, 1268, 1354, 1355) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Copeton Freshwater' WHERE raceid IN (989, 990, 1062, 1063, 1064) AND CanonicalRaceName IS NULL;  -- MERGED: 'Copeton Freshwater', 'Copeton 600m', 'Copeton Freshwater 5km', 'Copeton Freshwater 2km', 'Copeton 600m'
UPDATE dbo.Race SET CanonicalRaceName = 'Copeton Waters' WHERE raceid IN (1175, 1176, 1177) AND CanonicalRaceName IS NULL;  -- MERGED: 'Copeton Waters', 'Copeton Waters 2.5km', 'Copeton 600m'
UPDATE dbo.Race SET CanonicalRaceName = 'Cronulla' WHERE raceid IN (1080, 1081) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Cronulla Beach Fun' WHERE raceid IN (992) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Dee Why 750' WHERE raceid IN (895, 896) AND CanonicalRaceName IS NULL;  -- MERGED: 'Dee Why', 'Dee Why 750'
UPDATE dbo.Race SET CanonicalRaceName = 'Definition Health Clubs -Nth Curl Curl' WHERE raceid IN (623) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'DY2K' WHERE raceid IN (573, 592, 640, 683, 721) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Fingal Bay Swim' WHERE raceid IN (948, 1028, 1029, 1152, 1153) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Forresters Beach' WHERE raceid IN (703, 797, 833, 834, 923, 924, 995, 996, 997, 1067, 1068, 1185, 1186, 1260, 1261) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Forster' WHERE raceid IN (1056, 1057, 1321, 1322, 1323) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Forster Club to Club' WHERE raceid IN (695, 769, 910, 981, 982, 983, 1156, 1157, 1158, 1245, 1246, 1426) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Foster' WHERE raceid IN (653) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Freshwater' WHERE raceid IN (802, 1406) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Gaol Break Ocean Swim' WHERE raceid IN (600, 689, 737, 807, 1046) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Gerringong' WHERE raceid IN (1293) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Gosford Brisbane Water' WHERE raceid IN (686) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Hawks Nest' WHERE raceid IN (631) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Head2Head' WHERE raceid IN (942, 943, 1178) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Husky Ocean Swim' WHERE raceid IN (1140) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Ice Cold Classic' WHERE raceid IN (423) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Jervis Bay' WHERE raceid IN (1344, 1345, 1346, 1347) AND CanonicalRaceName IS NULL;  -- MERGED: 'Jervis Bay 3.8', 'Jervis Bay 1.9', 'Jervis Bay 1.5', 'Jervis Bay 750m'
UPDATE dbo.Race SET CanonicalRaceName = 'Jervis Bay Mini Swim' WHERE raceid IN (1144, 1145) AND CanonicalRaceName IS NULL;  -- MERGED: 'Jervis Bay 1km', 'Jervis Bay Mini Swim'
UPDATE dbo.Race SET CanonicalRaceName = 'Jim Kerry - Nth Wollongong' WHERE raceid IN (785) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Lake Macquarie' WHERE raceid IN (967, 1051, 1052) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Lake Macquarie Swim' WHERE raceid IN (889) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Long Reef' WHERE raceid IN (626, 666, 708, 750, 838, 839) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Macquarie Bondi to Bronte Ocean Swim' WHERE raceid IN (320, 321) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Manly' WHERE raceid IN (722, 726, 836, 837, 866, 867) AND CanonicalRaceName IS NULL;  -- MERGED: 'Manly', 'Manly 1 km', 'Manly1km', 'Manly 2km', 'Manly Blue Dolphins', 'Manly 1km Blue Dolphins'
UPDATE dbo.Race SET CanonicalRaceName = 'Manly Beginners Can Too' WHERE raceid IN (1104) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Manly Blue Dolphins' WHERE raceid IN (1018, 1019) AND CanonicalRaceName IS NULL;  -- MERGED: 'Manly Blue Dolphins', 'Manly 1km'
UPDATE dbo.Race SET CanonicalRaceName = 'Manly Blue Dolphins Ocean Swiim' WHERE raceid IN (933, 934) AND CanonicalRaceName IS NULL;  -- MERGED: 'Manly Blue Dolphins Ocean Swiim', 'Manly Blue Dolphins 1km'
UPDATE dbo.Race SET CanonicalRaceName = 'Manly Can Too' WHERE raceid IN (1106) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Manly Daily Swim' WHERE raceid IN (800, 801) AND CanonicalRaceName IS NULL;  -- MERGED: 'Manly Daily Swim', 'Manly 1km'
UPDATE dbo.Race SET CanonicalRaceName = 'Manly Kids Can Too' WHERE raceid IN (1103) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Manly Sprinters Can Too' WHERE raceid IN (1105) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Manly Steyne Swim' WHERE raceid IN (638) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Manly Warf' WHERE raceid IN (766) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Manly Warf Hotel' WHERE raceid IN (681, 684) AND CanonicalRaceName IS NULL;  -- MERGED: 'Manly Warf Hotel', 'Manly 1km'
UPDATE dbo.Race SET CanonicalRaceName = 'Manly Wharf Swim' WHERE raceid IN (765) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Monavale Cold Water' WHERE raceid IN (854) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Monavale Mighty Marathon' WHERE raceid IN (633, 674, 715) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Mone Vale to Warriewood' WHERE raceid IN (1341) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'NarraFun Ocean Swim' WHERE raceid IN (855, 918) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Newcastle' WHERE raceid IN (951) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Newcastle Harbour' WHERE raceid IN (1031, 1032, 1222, 1223, 1384) AND CanonicalRaceName IS NULL;  -- MERGED: 'Newcastle Harbour', 'Newcastle 700m', 'Newcastle 700m', 'Newcastle Harbour', 'Newcastle Harbour 700m'
UPDATE dbo.Race SET CanonicalRaceName = 'Newcastle Harbour Swim' WHERE raceid IN (678) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Newcastle Harbour Swim Classic' WHERE raceid IN (6, 7) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Newport to Avalon' WHERE raceid IN (1320) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Nile Mile Beach Classic' WHERE raceid IN (1350) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Nine Mile Beach' WHERE raceid IN (1351) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Nobbys to Newcastle' WHERE raceid IN (5, 932, 1017, 1139, 1206, 1299, 1385) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'North Curl Curl' WHERE raceid IN (1089, 1329, 1330) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'North Woolongong' WHERE raceid IN (641) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Nth Avoca Beach Fest' WHERE raceid IN (1015, 1016) AND CanonicalRaceName IS NULL;  -- MERGED: 'Nth Avoca Beach Fest', 'Nth Avoca 500m'
UPDATE dbo.Race SET CanonicalRaceName = 'Nth Bondi' WHERE raceid IN (822, 1025) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Nth Bondi Classic' WHERE raceid IN (635) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Nth Curl Curl' WHERE raceid IN (927) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Nth Curl Curl 3 Points' WHERE raceid IN (707) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Nth Steyne Swim - New Date' WHERE raceid IN (577) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Optus Swim Sydney Harbour' WHERE raceid IN (1496) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Pacific Palms' WHERE raceid IN (692, 904, 1061, 1166, 1167, 1242, 1327, 1328, 1414, 1415) AND CanonicalRaceName IS NULL;  -- MERGED: 'Pacific Palms', 'Pacific Palms', 'Pacific Palms', 'Pacific Palms 1.5', 'Pacific Palms 600m', 'Pacific Palms 600m', 'Pacific Palms', 'Pacific Palms 600m', 'Pacific Palms', 'Pacific Palms 600m'
UPDATE dbo.Race SET CanonicalRaceName = 'Palm Beach SLSA Enduro Champs' WHERE raceid IN (810) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Pool to Peak Swim' WHERE raceid IN (16, 17) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Proclamation Classic' WHERE raceid IN (18, 19, 20) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Quarter Mile Swim' WHERE raceid IN (27) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Queenscliff' WHERE raceid IN (847, 979, 1207, 1208, 1286, 1287) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Queenscliff Swim for Saxon' WHERE raceid IN (1037, 1038) AND CanonicalRaceName IS NULL;  -- MERGED: 'Queenscliff 800m', 'Queenscliff Swim for Saxon'
UPDATE dbo.Race SET CanonicalRaceName = 'Rock to Rock Pacific Palms' WHERE raceid IN (602, 650, 731, 772, 849, 975, 1243) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Roughwater' WHERE raceid IN (753, 874) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Sandon Point' WHERE raceid IN (971) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Shark Island Swim Classic' WHERE raceid IN (576, 598, 643, 844, 845, 897, 898, 991, 1049, 1050, 1163, 1164, 1388, 1389) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Shell Harbour' WHERE raceid IN (651) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Shellharbour' WHERE raceid IN (908, 1254, 1324) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Shellharbour Junior' WHERE raceid IN (1168, 1169, 1424, 1425) AND CanonicalRaceName IS NULL;  -- MERGED: 'Shellharbour Junior', 'Shellharbour', 'Shellharbour', 'Shellharbour Junior'
UPDATE dbo.Race SET CanonicalRaceName = 'Shellharbour Ocean Swim' WHERE raceid IN (977, 978) AND CanonicalRaceName IS NULL;  -- MERGED: 'Shellharbour 400m', 'Shellharbour Ocean Swim'
UPDATE dbo.Race SET CanonicalRaceName = 'South Head Roughwater' WHERE raceid IN (605, 1182, 1183, 1184) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'South Maroubra Ocean Swim' WHERE raceid IN (457, 458, 459, 1303, 1304, 1390, 1391, 1392) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Stanwell Park' WHERE raceid IN (649, 687, 732, 770, 843, 903, 968) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Stanwell Park Challenge' WHERE raceid IN (603, 1147, 1244) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Steyne Swim - Manly' WHERE raceid IN (593) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Sth Curl Curl' WHERE raceid IN (671) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Sth Curl Curl to Freshwater' WHERE raceid IN (993) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Sth West Rocks' WHERE raceid IN (963, 1047, 1048, 1149, 1150, 1236, 1237, 1238, 1334, 1335, 1336) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Swim for Saxon' WHERE raceid IN (913, 980) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Sydney HArbour Kids' WHERE raceid IN (1380, 1381) AND CanonicalRaceName IS NULL;  -- MERGED: 'Sydney Harbour', 'Sydney HArbour Kids'
UPDATE dbo.Race SET CanonicalRaceName = 'Sydney Harbour' WHERE raceid IN (727, 728, 949, 950, 1114, 1115) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Sydney Harbour Classic' WHERE raceid IN (596, 685, 763, 764, 805, 806) AND CanonicalRaceName IS NULL;  -- MERGED: 'Sydney Harbour Classic', 'Sydney Harbour Classic', 'Sydney Harbour Classic', 'Sydney Harbour 1km', 'Sydney Harbour Classic', 'Sydney Harbour 1km'
UPDATE dbo.Race SET CanonicalRaceName = 'Sydney Harbour Swim' WHERE raceid IN (639) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Sydney Harbour Swim Classic' WHERE raceid IN (575) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Sydney Shire' WHERE raceid IN (1263, 1264) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Tamarama to Clovelly' WHERE raceid IN (773, 808, 835, 890) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Tathra Wharf to Waves' WHERE raceid IN (614, 1108, 1109) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'The Great Sydney Swim' WHERE raceid IN (1113) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'The New Manly Swim' WHERE raceid IN (574) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'The Roughwater' WHERE raceid IN (12) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Tilbury Classic' WHERE raceid IN (655, 907, 976, 1058, 1165, 1239, 1411) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Toowoon Bay Ocean Swim' WHERE raceid IN (35, 36, 405, 624, 662, 705, 744, 928, 929, 1005, 1006, 1007, 1076, 1077, 1078, 1079, 1195, 1196, 1197, 1198, 1269, 1270, 1271, 1272, 1358, 1359, 1360) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'True Mile Swim' WHERE raceid IN (26) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'True Paddler Challenge' WHERE raceid IN (28) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Tweed River' WHERE raceid IN (663, 706, 862, 863, 1085, 1086) AND CanonicalRaceName IS NULL;  -- MERGED: 'Tweed River', 'Tweed River', 'Tweed River', 'Tweed River 1km', 'Tweed River', 'Tweed 1.2km'
UPDATE dbo.Race SET CanonicalRaceName = 'Tweed River - Murwillumbah' WHERE raceid IN (581) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Vladswim' WHERE raceid IN (1369, 1370, 1371) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'WA Open Water Swimming Series - Race 2' WHERE raceid IN (460, 461, 462, 463) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Warf to Waves' WHERE raceid IN (768) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Warriewood Ocean Swim' WHERE raceid IN (325, 358, 359, 360, 850, 1383) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Warriewood to MonaVale Ocean Swim' WHERE raceid IN (380) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Wollongong' WHERE raceid IN (964, 965) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Woy Woy' WHERE raceid IN (1071, 1072, 1073) AND CanonicalRaceName IS NULL;
UPDATE dbo.Race SET CanonicalRaceName = 'Woy Woy Marathon' WHERE raceid IN (1010, 1011, 1012, 1013) AND CanonicalRaceName IS NULL;  -- MERGED: 'Woy Woy Marathon', 'Woy Woy 2km', 'Woy Woy 1km', 'Woy Woy 400m'
UPDATE dbo.Race SET CanonicalRaceName = 'Yamba Ocean Swim' WHERE raceid IN (14, 15, 613, 627, 669, 712, 868, 869, 937, 938, 1020, 1021, 1096, 1097, 1213, 1214, 1288, 1302, 1374, 1375) AND CanonicalRaceName IS NULL; 